# Generated by Django 5.1.4 on 2025-05-08 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "email",
                    models.EmailField(max_length=50, primary_key=True, serialize=False),
                ),
                ("fullName", models.CharField(max_length=30)),
                ("password", models.CharField(max_length=20)),
                ("mobile", models.IntegerField(default=0)),
            ],
        ),
    ]
