# Generated by Django 5.1.4 on 2025-05-13 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("APP", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "AddId",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("fullName", models.CharField(max_length=30)),
                ("mobile", models.IntegerField(default=0)),
                ("alternateMobile", models.IntegerField(default=0)),
                ("pincode", models.IntegerField(default=0)),
                ("fullAddress", models.TextField(max_length=100)),
                ("landmark", models.TextField(max_length=50)),
                ("cityDistric", models.TextField(max_length=20)),
                ("state", models.TextField(max_length=20)),
                (
                    "email",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="APP.user"
                    ),
                ),
            ],
        ),
    ]
