# Generated by Django 5.1.4 on 2025-05-13 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("APP", "0002_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="address",
            name="country",
            field=models.TextField(max_length=20, null=True),
        ),
    ]
