# Generated by Django 5.1.4 on 2025-07-18 21:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("APP", "0003_address_country"),
    ]

    operations = [
        migrations.CreateModel(
            name="MyCart",
            fields=[
                (
                    "cartId",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("productsId", models.JSONField(default=dict)),
                (
                    "email",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="APP.user"
                    ),
                ),
            ],
        ),
    ]
