# Generated by Django 5.1.4 on 2025-07-19 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("APP", "0004_mycart"),
    ]

    operations = [
        migrations.RenameField(
            model_name="mycart",
            old_name="productsId",
            new_name="cartProducts",
        ),
    ]
