# Generated by Django 5.1.4 on 2025-07-19 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("APP", "0005_rename_productsid_mycart_cartproducts"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mycart",
            name="cartProducts",
        ),
        migrations.AddField(
            model_name="mycart",
            name="noOfProduct",
            field=models.IntegerField(default=0),
        ),
    ]
