# Generated by Django 5.1.4 on 2025-07-19 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("APP", "0006_remove_mycart_cartproducts_mycart_noofproduct"),
    ]

    operations = [
        migrations.DeleteModel(
            name="MyCart",
        ),
    ]
