# Generated by Django 5.1.4 on 2025-08-11 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("APP", "0007_delete_mycart"),
        ("Order", "0017_order_trackpathid"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentDetails",
            fields=[
                (
                    "paymentDetailsId",
                    models.BigIntegerField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("amount", models.FloatField(default=0)),
                ("date", models.DateField(null=True)),
                (
                    "email",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="APP.user"
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Order.order"
                    ),
                ),
            ],
        ),
    ]
