# Generated by Django 5.1.4 on 2025-07-19 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("APP", "0007_delete_mycart"),
        ("Products", "0007_alter_product_productprice"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "orderId",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                (
                    "address",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="APP.address"
                    ),
                ),
                (
                    "cart",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Products.mycart",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OrderPath",
            fields=[
                (
                    "orderPathId",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("confirmDate", models.DateField(null=True)),
                ("shippedDate", models.DateField(null=True)),
                ("outOfDeliveryDate", models.DateField(null=True)),
                ("deliveredDate", models.DateField(null=True)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Order.order"
                    ),
                ),
            ],
        ),
    ]
