# Generated by Django 5.1.4 on 2025-07-19 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Order", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderpath",
            name="cancelledDate",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="orderpath",
            name="refundDate",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="orderpath",
            name="returnDate",
            field=models.DateField(null=True),
        ),
    ]
