# Generated by Django 5.1.4 on 2025-07-19 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Order", "0002_orderpath_cancelleddate_orderpath_refunddate_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="totalPrice",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="order",
            name="cart",
            field=models.JSONField(default=dict),
        ),
    ]
