# Generated by Django 5.1.4 on 2025-07-19 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Order", "0003_order_totalprice_alter_order_cart"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="cart",
            new_name="cartsIds",
        ),
    ]
