# Generated by Django 5.1.4 on 2025-07-19 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Order", "0005_order_email"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="email",
        ),
    ]
