# Generated by Django 5.1.4 on 2025-07-19 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("APP", "0007_delete_mycart"),
        ("Order", "0006_remove_order_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="email",
            field=models.ForeignKey(
                default="null",
                on_delete=django.db.models.deletion.CASCADE,
                to="APP.user",
            ),
            preserve_default=False,
        ),
    ]
