# Generated by Django 5.1.4 on 2025-07-19 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Order", "0007_order_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="orderDate",
            field=models.DateField(auto_now=True),
        ),
    ]
