# Generated by Django 5.1.4 on 2025-07-19 16:08

import Products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Order", "0008_order_orderdate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="cartsIds",
            field=models.JSONField(default=Products.models.MyCart),
        ),
    ]
