# Generated by Django 5.1.4 on 2025-07-19 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Order", "0009_alter_order_cartsids"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="cartsIds",
            new_name="myCarts",
        ),
    ]
