# Generated by Django 5.1.4 on 2025-07-19 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Order", "0010_rename_cartsids_order_mycarts"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="myCarts",
            field=models.JSONField(default=dict),
        ),
    ]
