# Generated by Django 5.1.4 on 2025-07-19 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Order", "0011_alter_order_mycarts"),
        ("Products", "0007_alter_product_productprice"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="myCarts",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="Products.mycart"
            ),
        ),
    ]
