# Generated by Django 5.1.4 on 2025-07-19 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Order", "0012_alter_order_mycarts"),
        ("Products", "0007_alter_product_productprice"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="myCarts",
        ),
        migrations.AddField(
            model_name="order",
            name="myCarts",
            field=models.ManyToManyField(
                blank=True, related_name="orders", to="Products.mycart"
            ),
        ),
    ]
