# Generated by Django 5.1.4 on 2025-07-19 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Order", "0013_remove_order_mycarts_order_mycarts"),
        ("Products", "0007_alter_product_productprice"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="myCarts",
            field=models.ManyToManyField(blank=True, to="Products.mycart"),
        ),
    ]
