# Generated by Django 5.1.4 on 2025-07-19 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Order", "0014_alter_order_mycarts"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="myCarts",
        ),
        migrations.AddField(
            model_name="order",
            name="myCarts",
            field=models.JSONField(default=list),
        ),
    ]
