# Generated by Django 5.1.4 on 2025-07-20 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Order", "0015_remove_order_mycarts_order_mycarts"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="paymentStatus",
            field=models.BooleanField(default=False),
        ),
    ]
