# Generated by Django 5.1.4 on 2025-07-20 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Order", "0016_order_paymentstatus"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="trackPathId",
            field=models.BigIntegerField(null=True),
        ),
    ]
