# Generated by Django 5.1.4 on 2025-08-11 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Order", "0017_order_trackpathid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderpath",
            name="orderPathId",
            field=models.BigIntegerField(
                auto_created=True, primary_key=True, serialize=False
            ),
        ),
    ]
