# Generated by Django 5.1.4 on 2025-08-11 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Order", "0018_alter_orderpath_orderpathid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderpath",
            name="orderPathId",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False
            ),
        ),
    ]
