# Generated by Django 5.1.4 on 2025-08-11 22:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Order", "0019_alter_orderpath_orderpathid"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="trackPathId",
        ),
        migrations.AddField(
            model_name="order",
            name="trackPath",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tracked_orders",
                to="Order.orderpath",
            ),
        ),
    ]
