# Generated by Django 5.1.4 on 2025-07-17 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("APP", "0003_address_country"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "productId",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("productType", models.CharField(max_length=30)),
                ("productName", models.CharField(max_length=30)),
                ("productPrice", models.IntegerField()),
                ("productSpecisl", models.IntegerField()),
                ("productBrand", models.IntegerField()),
                ("productWork", models.IntegerField()),
                ("fullDetails", models.TextField(max_length=500)),
                ("images", models.JSONField(default=dict)),
                ("videos", models.JSONField(default=dict)),
                ("keysFeatures", models.JSONField(default=dict)),
                ("date", models.DateField(auto_now=True)),
                (
                    "sellerName",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="APP.user"
                    ),
                ),
            ],
        ),
    ]
