# Generated by Django 5.1.4 on 2025-07-17 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Products", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="sellerName",
            new_name="sellerEmail",
        ),
    ]
