# Generated by Django 5.1.4 on 2025-07-17 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Products", "0002_rename_sellername_product_selleremail"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="productSpecisl",
        ),
        migrations.AddField(
            model_name="product",
            name="productSpecial",
            field=models.CharField(default="null", max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="product",
            name="fullDetails",
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name="product",
            name="productBrand",
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name="product",
            name="productWork",
            field=models.CharField(max_length=30),
        ),
    ]
