# Generated by Django 5.1.4 on 2025-07-18 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "Products",
            "0003_remove_product_productspecisl_product_productspecial_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="productSpecial",
        ),
        migrations.AddField(
            model_name="product",
            name="productTitle",
            field=models.CharField(default="null", max_length=100),
            preserve_default=False,
        ),
    ]
