# Generated by Django 5.1.4 on 2025-07-19 05:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("APP", "0007_delete_mycart"),
        ("Products", "0004_remove_product_productspecial_product_producttitle"),
    ]

    operations = [
        migrations.CreateModel(
            name="MyCart",
            fields=[
                (
                    "cartId",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("noOfProduct", models.IntegerField(default=0)),
                (
                    "email",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="APP.user"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="Products.product",
                    ),
                ),
            ],
        ),
    ]
