# Generated by Django 5.1.4 on 2025-07-19 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Products", "0005_mycart"),
    ]

    operations = [
        migrations.AddField(
            model_name="mycart",
            name="price",
            field=models.FloatField(default=0),
        ),
    ]
