# Generated by Django 5.1.4 on 2025-07-19 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Products", "0006_mycart_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="productPrice",
            field=models.FloatField(default=0),
        ),
    ]
